### ISSUE TITLE
[App] reconnect count down on app closure 

### ISSUE THREAD

**Issue by mpe5651** [Blackjack92/fhvRobot#107]
there is a reproducable bug (at least on my htc one m7): when "Abbrechen" is pressed, the app closes, but the reconnect time out is left to count down.

![screenshot_2016-01-18-15-29-43](https://cloud.githubusercontent.com/assets/11227401/12394332/77cbea5e-bdfb-11e5-9e69-eb0ff492ed43.png)

**Comment by trylimits** [comment]
Is there any exception thrown?
What happens if you press _back_ instead of "Abbrechen"?

**Comment by mpe5651** [comment]
no, there is no exception at all. there is only a message "RoboApp wurde beendet" before the timer is displayed. pressing back or "abbrechen" stops the timer and you are in your phone's home menu. the most weird thing is that this app only occurs on my htc phone.

**Comment by trylimits** [comment]
Maybe this was because of #126 . Could you please try again with the newest version?

**Comment by trylimits** [comment]
@mpe5651 Could you please re-check if the bug still exists in the newest version?

**Comment by trylimits** [comment]
Acc. to @mpe5651 this bug is fixed.
