### ISSUE TITLE
[Game Server] delete entries from high score

### ISSUE THREAD

**Issue by mpe5651** [Blackjack92/fhvRobot#130]
delete false high socre entries

**Comment by trylimits** [comment]
Above commit implements this. The button for deleting is placed on the settings view.

To have access to the current selected item in the `ListView`s of the main model I have injected the `MainViewModel` to the `SettingsViewModel`. I'm not sure if this is the intended way to go in MVVM @Blackjack92 so you may correct if if it's not entirely correct.
