### ISSUE TITLE
[App] Implement GUI for App

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#14]
One should take care of implementing a dummy GUI for the app.

I suggest the following concept:

1. App forces landscape mode
2. Background/whole screen of the app is filled with camera image
3. Left and right side of the app allows to control motors by sliding with thumbs
4. Important messages should pop up in the lower part of the screen (Toasts)
5. Upper screen part should include some static information text (time, waiting list, ...)

The app lifecycle should be as follows:

1. Show a splash screen
1a.) Connect to the server (background task, actual implementation should be discussed in another ticket)
1a-success.) Go to the main screen
1a-fail.) Show Dialog (Retry, Cancel -> closes app)
2. Show main screen (as describe above)

**Comment by Blackjack92** [comment]
This ticket should be split in more tickets. Some parts of it are already implemented.
