### ISSUE TITLE
[App] Add "about us" page to welcome screen

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#145]
We should not be that shy!

Let's add an "about us" page to the welcome screen to introduce our-self.

**Comment by trylimits** [comment]
Should we add a page to the app intro or should we have a button somewhere to another activity which shows "about us" and maybe something like "faq" or whatever?

**Comment by Blackjack92** [comment]
I would add an "about us" page.

**Comment by trylimits** [comment]
Added a basic about us page as second page of the welcome pages.
