### ISSUE TITLE
[Command] [Server] [Robo] Drive Motors

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#17]
This ticket is about the implementation of the following command:

@Blackjack92 
From: Server
To: Robot
Command ID: `10` for right, `11` for left, `12` for both motors
Len: [1] (any other value should not be accepted by the Robot)
Payload: The actual value as signed byte (`-100 to 100`)

@trylimits
The Robot's policy should be:

1. Set the motor speed to the given value
2. If no motor command for >5s is received the Robot should stop (emergency mode)

**Comment by Blackjack92** [comment]
Please verify this functionality. There are three buttons on the server application.

**Comment by trylimits** [comment]
Works properly from the server and from the app. Not committed yet, as some clean-ups have to be made. Ticket #34 still relevant!

**Comment by trylimits** [comment]
Implemented command. Solved.

**Comment by trylimits** [comment]
On App- and Server-side the commands for controlling left/right motor are reversed.

We have to fix that and recompile the library.

**Comment by trylimits** [comment]
Fixed.
