### ISSUE TITLE
[Server] Disconnect from client should be noticed

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#2]
Implement a timeout, so that when the client is not "heart beating" a disconnect should take place.

**Comment by trylimits** [comment]
The responsibility to do this is on the Session Layer, i.e. the Session Layer has to create and run a heart beat thread which sends a specific heart beat packet to the receiver's Session Layer in a specific interval. If the Session Layer itself does not receive heart beats any more in an interval twice as long, it should callback the upper layers about the lost connection.

**Comment by Blackjack92** [comment]
I have already written a simple concept for doing that. It seems to be a little bit different but it should work.
