### ISSUE TITLE
[Server] [RoboServer] Remove .classpath and .project from .gitignore

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#20]
We must remove `.classpath` and `.project` from `.gitignore` of the _RoboServer_ project, as otherwise it will not resolve the referenced projects correctly and thus not build.
@Blackjack92 I guess you have to do that bc you are the only one who has those files locally.

**Comment by Blackjack92** [comment]
Should be fixed. Pls try to import it again.

**Comment by trylimits** [comment]
Verified fixed.
