### ISSUE TITLE
[Server] Decline session request if max number of clients reached

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#22]
At the moment the server just stops responding to session requests if there are no more session ids available. The server should send a response message with a declination flag and session id 0.

**Comment by trylimits** [comment]
I suggest to handle this case as follows:

To decline a session request, answer `0 0`. Robot code already handles this case correctly.

**Comment by Blackjack92** [comment]
This should be implemented pls verify it.

**Comment by trylimits** [comment]
I was not able to verify that. I tested it firing >200 session requests to the server and I just did not get any response at all after some time.

**Comment by trylimits** [comment]
Works now, except the fact, that session id `0` still shows up in the GUI if all session ids are reserved.

**Comment by trylimits** [comment]
I guess this can be considered as "fixed". The fact that clients with invalid session id still show up is ok. It's more like a feature than a bug.
