### ISSUE TITLE
[Server] Duplicate assignment of session ids

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#23]
It seems that the server assigns session ids more than once. See the following screenshot:

![image](https://cloud.githubusercontent.com/assets/7002180/11558736/a5b53558-99b4-11e5-8a20-e882e5718700.png)

To reproduce this issue just "fire" a bunch of session requests to the server (>5 per second).

I guess this is a multithreading issue of the receive thread.

**Comment by Blackjack92** [comment]
Please verify again. The "algorithm" for calculating a new session number has to be improved but for this another ticket should be opened when needed.

**Comment by trylimits** [comment]
Just did some testing and it seems that I am able to crash the server when firing a "bunch" of session requests. Looking at the code I guess it's because the server hangs in an endless loop if it fails to find a free session id.

Easy fix: Just implement a safe guard which declines the session request if it fails to get a free session id after 200 tries (should still be fast!). Then we should be fine.

**Comment by Blackjack92** [comment]
Pls verify the fix.

**Comment by trylimits** [comment]
Seems to work now.
