### ISSUE TITLE
[Server] [App] Fix packet size

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#34]
At the moment the packet size of send messages is 1024 byte this should be reduced to the real packet size.

**Comment by Blackjack92** [comment]
I will add the packet size to the network package, like mentioned in the protocol documentation.

**Comment by Blackjack92** [comment]
It is important that this is also fixed on the robo @trylimits.

**Comment by trylimits** [comment]
The Robot did not have this issue.

**Comment by Blackjack92** [comment]
The length byte was removed.
