### ISSUE TITLE
[Server] Heartbeat callback on remove

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#36]
When a client is removed because the hearbeat has not come, create a disconnected message.

**Comment by Blackjack92** [comment]
We have to decide if this is really necessary.

**Comment by trylimits** [comment]
In my opinion this is absolutely necessary. Connection losses are definitely occurring, either because of network problems, low power, forced app-closing or because of other reasons. If we do not recognize those scenarios we face undefined states of App/Server/Robot which is unsatisfying.

**Comment by Blackjack92** [comment]
This is not as important as the information when a application message is send and the send client is already disconnected. Because this callback message can be lost because the client is already dc.
I implemented it for the callback the other mentioned type should also be implemented.
