### ISSUE TITLE
[Server] Displaying stearing controllers

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#40]
Add a way for displaying the controllers which are stearing a robo.

**Comment by trylimits** [comment]
Do you have a proposal?

In my opinion we generally have to options:
Option 1: Complete "joystick" control for JavaFX for mouse control
Option 2: Implement keyboard control (4 keys for controlling left motor up/down and right motor up/down) and show current stearing state with sliders (as in app)

Option 2 will need less time to implement than Option 1.

**Comment by Blackjack92** [comment]
At the moment i would suggest to add two scrollbars like in the app and make them readonly, for showing the values from the app. Also a checkbox should be added which enables/disables the control from the app. 

For controlling from the server, the given option via buttons and value textfield is enough at the moment.

**Comment by trylimits** [comment]
@Blackjack92 This seems reasonable to me.

Don't you think it would be best if the Robot sends it's actual status to the server so that you can display those values instead of the sent ones? Would be more accurate.

**Comment by trylimits** [comment]
In Ticket #52 we already have implemented sliders to control the robot. Above commit additionally gives the possibility to control these sliders with the keys `W` and `S` for left motor up/down, `I` and `K` for right motor up/down and `D` and `J` for resetting the left and right motor.

The implementation uses the JavaFX timeline to animate the sliders after key presses/releases which is not perfect but that way we save one additional keyboard control thread.
