### ISSUE TITLE
[Server] Mediastreaming support

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#49]
Add a `DatagramSocket` which is listening to port 999. 
The port should answer with packet size + timestamp.

**Comment by Blackjack92** [comment]
The default socket is implemented and listening to incoming data.

**Comment by trylimits** [comment]
@Blackjack92 Could you please advice me how I can "push up" the received udp packets in the `MediaStreaming` class to my controller? I'm sure the current design already has something which does that, but I'm still not that familiar with it. I appreciate some hints.

**Comment by Blackjack92** [comment]
At the moment there are two different ways. The first one uses a `ClientController` and the second one is delegating over the `NetworkServer` for the `MediaStreaming` no specific implementation is done yet. 
If you want use the same infrastructure as for the `RoboCommunication` and `AppCommunication` you need to extend the `Communication` class.

**Comment by Blackjack92** [comment]
But i think it is not necessary to use this `Communication` because then you need to use our defined communication protocol also for the media data.

**Comment by trylimits** [comment]
If I got you correctly: The straight forward way would be to inject a callback into the `MediaStreaming` which is called if a packet is received? Seems ok to me.

**Comment by trylimits** [comment]
As all related tickets are closed this ticket is also done.
