### ISSUE TITLE
[Server] Test max packet size

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#50]
Test the max paket size for sending data to the server via the FHV network.

**Comment by Blackjack92** [comment]
Client application:
![image](https://cloud.githubusercontent.com/assets/11227428/11720050/e0f0527a-9f5d-11e5-8cf7-f35cc425f486.png)

**Comment by Blackjack92** [comment]
Server application:
![image](https://cloud.githubusercontent.com/assets/11227428/11720117/2753abcc-9f5e-11e5-8bec-520ed03deb23.png)

**Comment by Blackjack92** [comment]
On the server side it is visible that there is a jump about 47000 byte

**Comment by trylimits** [comment]
Nice test. As discussed we should cap the media stream packet size to 32kB.
