### ISSUE TITLE
[Server] [App] Reconnect when disconnected

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#62]
Reconnect when app is disconnected.

**Comment by trylimits** [comment]
At the moment connection loss is reported to the user and the app handles this event correctly by switching to the login screen.

In my opinion the app should not (must not) reconnect automatically/autonomously without letting the user interact. From a usability point of view it would make more sense to let the user decide if (and when) she/he wants to reconnect. This possibility is already provided by the app.

@Blackjack92 What's your opinion on that topic?
@mpe5651 You're also welcome to share your thoughts of course :)

**Comment by mpe5651** [comment]
I would also not let the app reconnect automatically. Maybe a reconnect button or something similar in combination with a timeout would address this issue.

**Comment by Blackjack92** [comment]
I think that there are two points.
1. It is good to ask the user for reconnect
2. It is bad, when we are in the FHV network and there are always disconnects

**Comment by mpe5651** [comment]
after discussion:
- if disconnected, a gray overlay appears
- 10 seconds countdown to automatic reconnect
- tapping to gray overlay starts reconnect immediately
- abort button allows return to login screen

**Comment by trylimits** [comment]
Above commit implements this behavior
