### ISSUE TITLE
[App] Usability & Styling

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#64]
Styling of the app so that it is more user friendly and easy to use.

Some proposals:

1. ~~Either hide notification bar or increase top margin of sliders~~
2. ~~Snap back of seekbar after touch release~~

**Comment by trylimits** [comment]
For usability reasons it is important that the App is running in full "fullscreen", i.e., the notification bar is hidden.

Alternatively, we have to give the sliders more margin at the top.

**Comment by trylimits** [comment]
Above commit also (among other things) improves the sliders (more top margin) which allows better control of the robot.

**Comment by trylimits** [comment]
Above commit implements snap back of seek bar if released.

**Comment by trylimits** [comment]
Above commit implements a "Signal Strength" image in the top right of the app which indicates signal strength (packet loss).

**Comment by trylimits** [comment]
Because of the implemented #31 the general style of the App has to be changed to (more modern) Holo theme which made the SeekBars look a little bit weird. We should discuss the exact styling of the SeekBar for controlling the motors.

**Comment by trylimits** [comment]
Above commit improves the styling of the app (see commit message).

**Comment by mpe5651** [comment]
after discussion:
- add fhv picture while connecting to stream https://upload.wikimedia.org/wikipedia/commons/0/07/Fachhochschule_Vorarlberg_1.jpg

**Comment by trylimits** [comment]
I think this can be closed. Style changes should be handled in more specific tickets as basic styling is already done.
