### ISSUE TITLE
[Server] Add server heartbeat

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#66]
Add a heartbeat which is send from the server. So every client knows if the server is still online.

**Comment by Blackjack92** [comment]
The heartbeat from the server is added. It should be used on the robo and the app @trylimits @mpe5651. This can be done in a different ticket.

**Comment by trylimits** [comment]
Could you please summarize the behavior of the heartbeat and what the server expects from the clients? Can I (as robot) just disconnect if I do not receive any heartbeat messages within 5 seconds?

**Comment by trylimits** [comment]
Above commit implements disconnect/reconnect if the heartbeat from the server is missing for more than 5s.

We should implement the same/similar behavior for the App client.

**Comment by Blackjack92** [comment]
The heartbeat is send from the server to each client (robo and app). The heartbeat contains 
```
as application flags: 0x00
as application command: 0x00
as payload: new byte[] { 0 }
```

It does not expect any response from the clients. You can disconnect when you do not receive any heartbeats for a specific duration (e.g. 5 seconds).

**Comment by trylimits** [comment]
The app now handles missing server heartbeats and closes the app safely (with message) when hb is missing for >5s. I also introduced a signal strength "image" depending on the information.
