### ISSUE TITLE
[Server] Slow communication on some machines

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#68]
I observe very slow communication between Server and client instances on my local machine. The problem only occurs if the Robot is connected, i.e. an additional network interface is present.

**Comment by trylimits** [comment]
It took some time to track down the problem. I tried several things to solve this issue, including:

1. Replacing lookup of `InetAddress` by getting this information directly from the received packet, i.e. object of type `SocketAddress`
2. Debugging received and sent messages

Finally, I figured out that the method for generating a new session id is causing the issue. To be more precise, the call
```
			newSession = ThreadLocalRandom.current().nextInt(minSession, maxSession);
```
took between 2 and 5 seconds on my machine. Strangely, this only affects the first call. I solved this issue by putting the first call of `ThreadLocalRandom.current()` into a static initializer of the using class.

**Comment by trylimits** [comment]
Above commits implement these changes.

**Comment by trylimits** [comment]
Above comments and corresponding commits did not entirely solve the problem. The actual cause of the problem was the lookup of the sender's ip address of a `DatagramPacket`.

Some more debugging showed, that the call of `myDatagramPacket.getAddress().getHostName()` caused the performance issue. This call performs a reverse DNS lookup of the sender which can obviously be very slow. See this question on SO: http://stackoverflow.com/questions/11795167/datagrampacket-getaddress-gethostname-is-blocking-my-thread

Replacing these calls according to the answer of the above question solved the issue completely. Above commit implements this.

**Comment by Blackjack92** [comment]
Pls check the `DatagramFactory` again there was a bug with `SocketException`.

**Comment by Blackjack92** [comment]
@trylimits can this issue be closed again?

**Comment by trylimits** [comment]
Yes :)

**Comment by trylimits** [comment]
Since this `ThreadLocalRandom` is not supported by android but still causes performance issues, we should replace this call.

**Comment by trylimits** [comment]
Done. No performance issues remaining.
