### ISSUE TITLE
[App] Add operator state

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#70]
Add the operator state from the server also to the app.

**Comment by trylimits** [comment]
Am I right, that (on app side) we just have to set the visibility state of the progress bars if we receive the command `ROBO_STEARING`/`ROBO_NOT_STEARING` and maybe show a message "Spectator mode"?

**Comment by Blackjack92** [comment]
Yes thats correct.

**Comment by mpe5651** [comment]
above commit implements this :-)
