### ISSUE TITLE
[App] Refactoring of controllers

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#72]
Atm. the `MainActivity` instantiates the `NetworkClient` and starts it.
Because of the additional `MediaStreaming` we should refactor the `NetworkClient` to `CommunicationClient` and should introduce a new class `NetworkClient` which is responsible for instantiating and starting both network services.

**Comment by Blackjack92** [comment]
So the `NetworkClient` contains the `MediaStreaming` and the `CommunicationClient`.

**Comment by trylimits** [comment]
Exactly. I will take care of this.

**Comment by trylimits** [comment]
Done as proposed.
