### ISSUE TITLE
[Robot] Compass sensor

### ISSUE THREAD

**Issue by mpe5651** [Blackjack92/fhvRobot#75]
- finish board for boosterpack
- process raw data to extract actual angle of device
- possibly use angle data of all three axis

**Comment by trylimits** [comment]
Current state:

1. Board is finished (including lidar)
2. I2C API to access the sensors finished

Still to do:

Initializing the board and fetching the correct values.

**Comment by trylimits** [comment]
Finally, I got the compass sensor working properly. The compass sensor is accessed directly through it's I2C interface `0x0C`.
