### ISSUE TITLE
[App] compass control

### ISSUE THREAD

**Issue by mpe5651** [Blackjack92/fhvRobot#78]

**Comment by mpe5651** [comment]
I've done some research about free javafx compass controls. unfortunately, it seems that there is not really much around. I think we'll have to adjust a gauge to a compass. there are some code examples for gauges like http://www.codetown.us/profiles/blogs/javafx-and-steelseries-gauges-using-fxml and libraries like http://www.hameister.org/JavaFX_JFXtrasLib.html which could be useful for our app.

**Comment by trylimits** [comment]
After thinking about this issue I think we should not add a conventional compass control like this one:

**Comment by mpe5651** [comment]
the line compass should be finished. please verify if it's like you need and then close this ticket.
