### ISSUE TITLE
[App] Improve steering behavior

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#87]

**Comment by Blackjack92** [comment]
@trylimits pls can you check this ticket.
E.g. try to change the current step size from 10 to 20.

**Comment by trylimits** [comment]
I don't think increasing the step size of the sliders improve this behavior.
I guess the problem is because the onchange events of the slider trigger at slightly different times. I think we should improve this behavior in order to improve the general behavior.

**Comment by trylimits** [comment]
I have done some testing with limited motor power and this seems to solve the problem. See ticket #181 for how to set the motor power factor in the config file.
