### ISSUE TITLE
[Protocol] Add extended payload length bit

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#91]
Add extended payload length bit to the server, like mentioned in https://github.com/Blackjack92/fhvRobot/wiki/Protocol-definitions. This ticket is solved when app, server and gaming server can handle this bit and the extended payload.

**Comment by mpe5651** [comment]
is in progress. will probably be finished on thursday (when the nightmare called sensor systems exam is over).

**Comment by Blackjack92** [comment]
Perfect, so it is possible to try it together with the `GameServer`. Ticket #93 Should be solved but not tested.

**Comment by mpe5651** [comment]
above commit implements extended flag for server and app
