### ISSUE TITLE
[Server] Implement persist commands

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#97]
Implement the commands for persisiting data on the server.

```
PERSIST_DATA = 60
REQUEST_PERSISTED_DATA = 61
```

See wiki: https://github.com/Blackjack92/fhvRobot/wiki/Command-definitions

Also the depending logic should be implemented (E.g. a `PersistencyManager` like in the `GameServer`). This `PersistencyManager` is able to store the data to an xml file e.g. when the server is should down. Also this manager should be able to load data from the xml file and persist it in the memory e.g. as string.

**Comment by mpe5651** [comment]
persisting data to xml file form server is pending
